#!/usr/bin/env bash

sudo apt-get  update
sudo apt-get -y install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo sed -i "12i\\\tadd_header X-Served-By ${hostname};" /etc/nginx/sites-available/default
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo nginx -t
sudo service nginx restart
