#!/usr/bin/env bash
# Installs a load balancer
sudo apt -y update
sudo apt -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen 531536-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\ntoption httpclose\n\toption forwardfor\n\tserver 531536-web-02 54.162.4.175:80 check\n\tserver 531536-web-01 3.85.141.134:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
