#!/usr/bin/env bash
# This script is for displaying "Best School" 10 times using the while loop
i=1
while [ $i -le 10 ]
do
	echo "Best School"
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	(( i++ ))
done
exit 0
