#!/usr/bin/env bash
# This script is for displaying "Best School" 10 times using the while loop
i=0
while [ $i -lt 10 ]
do
	if [ $i != 8 ]
	then
		echo "Best School"
	else
		echo "Hi"
	fi
	(( i++ ))
done
exit 0
